--- a/.github/workflows/build_micropython.yml
+++ b/.github/workflows/build_micropython.yml
@@ -35,4 +35,4 @@
     - name: Build the unix port
       run: make -j $(nproc) -C ports/unix VARIANT=dev DEBUG=1
     - name: Run tests      
-      run: lib/lv_bindings/tests/run.sh
+      run: lib/lv_bindings/tests/run.sh